#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.

mysqldump -u root -p "$1" tyrell_corp > backup.sql
mydate=$(date +%d-%m-%Y)
tar -czvf "$mydate.tar.gz" backup.sql
